package org.mesdag.advjs.util;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.stats.StatType;
import net.minecraft.stats.Stats;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;

public interface StatsWrapper {
    StatType<Block> BLOCK_MINED = Stats.BLOCK_MINED;
    StatType<Item> ITEM_CRAFTED = Stats.ITEM_CRAFTED;
    StatType<Item> ITEM_USED = Stats.ITEM_USED;
    StatType<Item> ITEM_BROKEN = Stats.ITEM_BROKEN;
    StatType<Item> ITEM_PICKED_UP = Stats.ITEM_PICKED_UP;
    StatType<Item> ITEM_DROPPED = Stats.ITEM_DROPPED;
    StatType<EntityType<?>> KILLED = Stats.ENTITY_KILLED;
    StatType<EntityType<?>> KILLED_BY = Stats.ENTITY_KILLED_BY;
    StatType<ResourceLocation> CUSTOM = Stats.CUSTOM;

    ResourceLocation LEAVE_GAME = new ResourceLocation("leave_game");
    ResourceLocation PLAY_TIME = new ResourceLocation("play_time");
    ResourceLocation TOTAL_WORLD_TIME = new ResourceLocation("total_world_time");
    ResourceLocation TIME_SINCE_DEATH = new ResourceLocation("time_since_death");
    ResourceLocation TIME_SINCE_REST = new ResourceLocation("time_since_rest");
    ResourceLocation CROUCH_TIME = new ResourceLocation("sneak_time");
    ResourceLocation WALK_ONE_CM = new ResourceLocation("walk_one_cm");
    ResourceLocation CROUCH_ONE_CM = new ResourceLocation("crouch_one_cm");
    ResourceLocation SPRINT_ONE_CM = new ResourceLocation("sprint_one_cm");
    ResourceLocation WALK_ON_WATER_ONE_CM = new ResourceLocation("walk_on_water_one_cm");
    ResourceLocation FALL_ONE_CM = new ResourceLocation("fall_one_cm");
    ResourceLocation CLIMB_ONE_CM = new ResourceLocation("climb_one_cm");
    ResourceLocation FLY_ONE_CM = new ResourceLocation("fly_one_cm");
    ResourceLocation WALK_UNDER_WATER_ONE_CM = new ResourceLocation("walk_under_water_one_cm");
    ResourceLocation MINECART_ONE_CM = new ResourceLocation("minecart_one_cm");
    ResourceLocation BOAT_ONE_CM = new ResourceLocation("boat_one_cm");
    ResourceLocation PIG_ONE_CM = new ResourceLocation("pig_one_cm");
    ResourceLocation HORSE_ONE_CM = new ResourceLocation("horse_one_cm");
    ResourceLocation AVIATE_ONE_CM = new ResourceLocation("aviate_one_cm");
    ResourceLocation SWIM_ONE_CM = new ResourceLocation("swim_one_cm");
    ResourceLocation STRIDER_ONE_CM = new ResourceLocation("strider_one_cm");
    ResourceLocation JUMP = new ResourceLocation("jump");
    ResourceLocation DROP = new ResourceLocation("drop");
    ResourceLocation DAMAGE_DEALT = new ResourceLocation("damage_dealt");
    ResourceLocation DAMAGE_DEALT_ABSORBED = new ResourceLocation("damage_dealt_absorbed");
    ResourceLocation DAMAGE_DEALT_RESISTED = new ResourceLocation("damage_dealt_resisted");
    ResourceLocation DAMAGE_TAKEN = new ResourceLocation("damage_taken");
    ResourceLocation DAMAGE_BLOCKED_BY_SHIELD = new ResourceLocation("damage_blocked_by_shield");
    ResourceLocation DAMAGE_ABSORBED = new ResourceLocation("damage_absorbed");
    ResourceLocation DAMAGE_RESISTED = new ResourceLocation("damage_resisted");
    ResourceLocation DEATHS = new ResourceLocation("deaths");
    ResourceLocation MOB_KILLS = new ResourceLocation("mob_kills");
    ResourceLocation ANIMALS_BRED = new ResourceLocation("animals_bred");
    ResourceLocation PLAYER_KILLS = new ResourceLocation("player_kills");
    ResourceLocation FISH_CAUGHT = new ResourceLocation("fish_caught");
    ResourceLocation TALKED_TO_VILLAGER = new ResourceLocation("talked_to_villager");
    ResourceLocation TRADED_WITH_VILLAGER = new ResourceLocation("traded_with_villager");
    ResourceLocation EAT_CAKE_SLICE = new ResourceLocation("eat_cake_slice");
    ResourceLocation FILL_CAULDRON = new ResourceLocation("fill_cauldron");
    ResourceLocation USE_CAULDRON = new ResourceLocation("use_cauldron");
    ResourceLocation CLEAN_ARMOR = new ResourceLocation("clean_armor");
    ResourceLocation CLEAN_BANNER = new ResourceLocation("clean_banner");
    ResourceLocation CLEAN_SHULKER_BOX = new ResourceLocation("clean_shulker_box");
    ResourceLocation INTERACT_WITH_BREWINGSTAND = new ResourceLocation("interact_with_brewingstand");
    ResourceLocation INTERACT_WITH_BEACON = new ResourceLocation("interact_with_beacon");
    ResourceLocation INSPECT_DROPPER = new ResourceLocation("inspect_dropper");
    ResourceLocation INSPECT_HOPPER = new ResourceLocation("inspect_hopper");
    ResourceLocation INSPECT_DISPENSER = new ResourceLocation("inspect_dispenser");
    ResourceLocation PLAY_NOTEBLOCK = new ResourceLocation("play_noteblock");
    ResourceLocation TUNE_NOTEBLOCK = new ResourceLocation("tune_noteblock");
    ResourceLocation POT_FLOWER = new ResourceLocation("pot_flower");
    ResourceLocation TRIGGER_TRAPPED_CHEST = new ResourceLocation("trigger_trapped_chest");
    ResourceLocation OPEN_ENDERCHEST = new ResourceLocation("open_enderchest");
    ResourceLocation ENCHANT_ITEM = new ResourceLocation("enchant_item");
    ResourceLocation PLAY_RECORD = new ResourceLocation("play_record");
    ResourceLocation INTERACT_WITH_FURNACE = new ResourceLocation("interact_with_furnace");
    ResourceLocation INTERACT_WITH_CRAFTING_TABLE = new ResourceLocation("interact_with_crafting_table");
    ResourceLocation OPEN_CHEST = new ResourceLocation("open_chest");
    ResourceLocation SLEEP_IN_BED = new ResourceLocation("sleep_in_bed");
    ResourceLocation OPEN_SHULKER_BOX = new ResourceLocation("open_shulker_box");
    ResourceLocation OPEN_BARREL = new ResourceLocation("open_barrel");
    ResourceLocation INTERACT_WITH_BLAST_FURNACE = new ResourceLocation("interact_with_blast_furnace");
    ResourceLocation INTERACT_WITH_SMOKER = new ResourceLocation("interact_with_smoker");
    ResourceLocation INTERACT_WITH_LECTERN = new ResourceLocation("interact_with_lectern");
    ResourceLocation INTERACT_WITH_CAMPFIRE = new ResourceLocation("interact_with_campfire");
    ResourceLocation INTERACT_WITH_CARTOGRAPHY_TABLE = new ResourceLocation("interact_with_cartography_table");
    ResourceLocation INTERACT_WITH_LOOM = new ResourceLocation("interact_with_loom");
    ResourceLocation INTERACT_WITH_STONECUTTER = new ResourceLocation("interact_with_stonecutter");
    ResourceLocation BELL_RING = new ResourceLocation("bell_ring");
    ResourceLocation RAID_TRIGGER = new ResourceLocation("raid_trigger");
    ResourceLocation RAID_WIN = new ResourceLocation("raid_win");
    ResourceLocation INTERACT_WITH_ANVIL = new ResourceLocation("interact_with_anvil");
    ResourceLocation INTERACT_WITH_GRINDSTONE = new ResourceLocation("interact_with_grindstone");
    ResourceLocation TARGET_HIT = new ResourceLocation("target_hit");
    ResourceLocation INTERACT_WITH_SMITHING_TABLE = new ResourceLocation("interact_with_smithing_table");
}
