package org.mesdag.advjs.util;


import net.minecraft.block.Block;
import net.minecraft.entity.EntityType;
import net.minecraft.item.Item;
import net.minecraft.stat.StatType;
import net.minecraft.stat.Stats;
import net.minecraft.util.Identifier;

public interface StatsWrapper {
    StatType<Block> BLOCK_MINED = Stats.MINED;
    StatType<Item> ITEM_CRAFTED = Stats.CRAFTED;
    StatType<Item> ITEM_USED = Stats.USED;
    StatType<Item> ITEM_BROKEN = Stats.BROKEN;
    StatType<Item> ITEM_PICKED_UP = Stats.PICKED_UP;
    StatType<Item> ITEM_DROPPED = Stats.DROPPED;
    StatType<EntityType<?>> KILLED = Stats.KILLED;
    StatType<EntityType<?>> KILLED_BY = Stats.KILLED_BY;
    StatType<Identifier> CUSTOM = Stats.CUSTOM;

    Identifier LEAVE_GAME = Stats.LEAVE_GAME;
    Identifier PLAY_TIME = Stats.PLAY_TIME;
    Identifier TOTAL_WORLD_TIME = Stats.TOTAL_WORLD_TIME;
    Identifier TIME_SINCE_DEATH = Stats.TIME_SINCE_DEATH;
    Identifier TIME_SINCE_REST = Stats.TIME_SINCE_REST;
    Identifier CROUCH_TIME = Stats.PLAY_TIME;
    Identifier WALK_ONE_CM = Stats.WALK_ONE_CM;
    Identifier CROUCH_ONE_CM = Stats.CROUCH_ONE_CM;
    Identifier SPRINT_ONE_CM = Stats.SPRINT_ONE_CM;
    Identifier WALK_ON_WATER_ONE_CM = Stats.WALK_ON_WATER_ONE_CM;
    Identifier FALL_ONE_CM = Stats.FALL_ONE_CM;
    Identifier CLIMB_ONE_CM = Stats.CLIMB_ONE_CM;
    Identifier FLY_ONE_CM = Stats.FLY_ONE_CM;
    Identifier WALK_UNDER_WATER_ONE_CM = Stats.WALK_UNDER_WATER_ONE_CM;
    Identifier MINECART_ONE_CM = Stats.MINECART_ONE_CM;
    Identifier BOAT_ONE_CM = Stats.BOAT_ONE_CM;
    Identifier PIG_ONE_CM = Stats.PIG_ONE_CM;
    Identifier HORSE_ONE_CM = Stats.HORSE_ONE_CM;
    Identifier AVIATE_ONE_CM = Stats.AVIATE_ONE_CM;
    Identifier SWIM_ONE_CM = Stats.SWIM_ONE_CM;
    Identifier STRIDER_ONE_CM = Stats.STRIDER_ONE_CM;
    Identifier JUMP = Stats.JUMP;
    Identifier DROP = Stats.DROP;
    Identifier DAMAGE_DEALT = Stats.DAMAGE_DEALT;
    Identifier DAMAGE_DEALT_ABSORBED = Stats.DAMAGE_DEALT_ABSORBED;
    Identifier DAMAGE_DEALT_RESISTED = Stats.DAMAGE_DEALT_RESISTED;
    Identifier DAMAGE_TAKEN = Stats.DAMAGE_TAKEN;
    Identifier DAMAGE_BLOCKED_BY_SHIELD = Stats.DAMAGE_BLOCKED_BY_SHIELD;
    Identifier DAMAGE_ABSORBED = Stats.DAMAGE_ABSORBED;
    Identifier DAMAGE_RESISTED = Stats.DAMAGE_RESISTED;
    Identifier DEATHS = Stats.DEATHS;
    Identifier MOB_KILLS = Stats.MOB_KILLS;
    Identifier ANIMALS_BRED = Stats.ANIMALS_BRED;
    Identifier PLAYER_KILLS = Stats.PLAYER_KILLS;
    Identifier FISH_CAUGHT = Stats.FISH_CAUGHT;
    Identifier TALKED_TO_VILLAGER = Stats.TALKED_TO_VILLAGER;
    Identifier TRADED_WITH_VILLAGER = Stats.TRADED_WITH_VILLAGER;
    Identifier EAT_CAKE_SLICE = Stats.EAT_CAKE_SLICE;
    Identifier FILL_CAULDRON = Stats.FILL_CAULDRON;
    Identifier USE_CAULDRON = Stats.USE_CAULDRON;
    Identifier CLEAN_ARMOR = Stats.CLEAN_ARMOR;
    Identifier CLEAN_BANNER = Stats.CLEAN_BANNER;
    Identifier CLEAN_SHULKER_BOX = Stats.CLEAN_SHULKER_BOX;
    Identifier INTERACT_WITH_BREWINGSTAND = Stats.INTERACT_WITH_BREWINGSTAND;
    Identifier INTERACT_WITH_BEACON = Stats.INTERACT_WITH_BEACON;
    Identifier INSPECT_DROPPER = Stats.INSPECT_DROPPER;
    Identifier INSPECT_HOPPER = Stats.INSPECT_HOPPER;
    Identifier INSPECT_DISPENSER = Stats.INSPECT_DISPENSER;
    Identifier PLAY_NOTEBLOCK = Stats.PLAY_NOTEBLOCK;
    Identifier TUNE_NOTEBLOCK = Stats.TUNE_NOTEBLOCK;
    Identifier POT_FLOWER = Stats.POT_FLOWER;
    Identifier TRIGGER_TRAPPED_CHEST = Stats.TRIGGER_TRAPPED_CHEST;
    Identifier OPEN_ENDERCHEST = Stats.OPEN_ENDERCHEST;
    Identifier ENCHANT_ITEM = Stats.ENCHANT_ITEM;
    Identifier PLAY_RECORD = Stats.PLAY_RECORD;
    Identifier INTERACT_WITH_FURNACE = Stats.INTERACT_WITH_FURNACE;
    Identifier INTERACT_WITH_CRAFTING_TABLE = Stats.INTERACT_WITH_CRAFTING_TABLE;
    Identifier OPEN_CHEST = Stats.OPEN_CHEST;
    Identifier SLEEP_IN_BED = Stats.SLEEP_IN_BED;
    Identifier OPEN_SHULKER_BOX = Stats.OPEN_SHULKER_BOX;
    Identifier OPEN_BARREL = Stats.OPEN_BARREL;
    Identifier INTERACT_WITH_BLAST_FURNACE = Stats.INTERACT_WITH_BLAST_FURNACE;
    Identifier INTERACT_WITH_SMOKER = Stats.INTERACT_WITH_SMOKER;
    Identifier INTERACT_WITH_LECTERN = Stats.INTERACT_WITH_LECTERN;
    Identifier INTERACT_WITH_CAMPFIRE = Stats.INTERACT_WITH_CAMPFIRE;
    Identifier INTERACT_WITH_CARTOGRAPHY_TABLE = Stats.INTERACT_WITH_CARTOGRAPHY_TABLE;
    Identifier INTERACT_WITH_LOOM = Stats.INTERACT_WITH_LOOM;
    Identifier INTERACT_WITH_STONECUTTER = Stats.INTERACT_WITH_STONECUTTER;
    Identifier BELL_RING = Stats.BELL_RING;
    Identifier RAID_TRIGGER = Stats.RAID_TRIGGER;
    Identifier RAID_WIN = Stats.RAID_WIN;
    Identifier INTERACT_WITH_ANVIL = Stats.INTERACT_WITH_ANVIL;
    Identifier INTERACT_WITH_GRINDSTONE = Stats.INTERACT_WITH_GRINDSTONE;
    Identifier TARGET_HIT = Stats.TARGET_HIT;
    Identifier INTERACT_WITH_SMITHING_TABLE = Stats.INTERACT_WITH_SMITHING_TABLE;
}
